name = "BlockMatching"
uuid = "100fd195-2f51-49a3-864c-eaaf5f23bc5e"
authors = ["Johnny Chen <johnnychen94@hotmail.com>"]
version = "0.1.0"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
Distances = "0.9, 0.10"
OffsetArrays = "1"
julia = "1"
