name = "BlockMatching"
uuid = "100fd195-2f51-49a3-864c-eaaf5f23bc5e"
authors = ["Johnny Chen <johnnychen94@hotmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
