name = "BlockMatching"
uuid = "100fd195-2f51-49a3-864c-eaaf5f23bc5e"
authors = ["Johnny Chen <johnnychen94@hotmail.com>"]
version = "0.1.0"

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
OffsetArrays = "1"
julia = "1"

[extras]
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"

[targets]
test = ["Images", "Test", "TestImages"]
